### ISSUE TITLE
Unable to build with OpenSSL 1.1.0h

### ISSUE THREAD

**Issue by guimard** [apowers313/fido2-server-demo#5]
Hello,

when compiling with OpenSSL 1.1.0h, I've the following errors:
```
../src/core/bn.cpp:37:29: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
   constant_time_le_size_t(in->dmax, i), in->dmax - 1, i)];
                             ^~
...
../src/core/bn.cpp:37:43: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
   constant_time_le_size_t(in->dmax, i), in->dmax - 1, i)];
                                           ^~
...
../src/core/bn.cpp:39:62: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
  return constant_time_select_ulong(constant_time_le_size_t(in->top, i), 0, l);
                                                              ^~
```

**Comment by apowers313** [comment]
Thanks a for the heads up. A little more context might help:
* What version of node.js are you running?
* What OS / version are you on?
* Assuming this during `npm install` can you see what package is having the error?

**Comment by guimard** [comment]
Hello,
I'm using Debian/Buster (testing) with Node.js 8.11.2. In [attached file](https://github.com/apowers313/fido2-server-demo/files/2100799/fido2-server-demo.log), you'll find the full log of:

    (git clone --recursive https://github.com/apowers313/fido2-server-demo && cd fido2-server-demo && npm install && npm start) 2>&1 | tee fido2-server-demo.log

Regards,
Xavier

[fido2-server-demo.log](https://github.com/apowers313/fido2-server-demo/files/2100799/fido2-server-demo.log)

**Comment by apowers313** [comment]
Thanks, looks like a problem with [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl).

Based on [this issue](https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/121) it looks like the solution might be to upgrade to node v9+?

**Comment by apowers313** [comment]
Might be node v10+ -- see apowers313/fido2-lib#10

**Comment by davedoesdev** [comment]
Works fine for me on Node v8.11.3

**Comment by davedoesdev** [comment]
Maybe it's picking up a different OpenSSL version

**Comment by guimard** [comment]
@davedoesdev : thanks, I'll try that

**Comment by davedoesdev** [comment]
@guimard the logs you attached show identical errors to https://github.com/apowers313/fido2-lib/issues/10 so this should be fixed. Somehow you must be picking up an old node-webcrypto-ossl

**Comment by davedoesdev** [comment]
@guimard could you supply the output from:

```bash
cd data
npm ls
```

Hopefully it may show the version of `node-webcrypto-ossl` that's getting pulled in

**Comment by rmhrisk** [comment]
NodeJs v8 doesn't support OpenSSL v1.1.0, you need to use OpenSSL v1.0.2 or update NodeJS to v10

**Comment by apowers313** [comment]
@rmhrisk Just out of curiosity, why doesn't `node-webcrypto-ossl` use the version of OpenSSL built in to node (via the `crypto` module)?

**Comment by rmhrisk** [comment]
Because the crypto module does not support all of the same capabilities necessary to expose webcrypto functionality.

**Comment by davedoesdev** [comment]
It's strange because on my machine it _does_ use the version of OpenSSL shipped with Node. See the log of my original bug: https://github.com/apowers313/fido2-lib/issues/10#issue-322615644

**Comment by davedoesdev** [comment]
Since the fix is using the Node version to determine the code path, the problem here is because the system OpenSSL is being used instead of the one in Node. But that doesn't happen on all machine evidently.

**Comment by davedoesdev** [comment]
@apowers313 how are the components compiled? Do they use node-gyp?

**Comment by guimard** [comment]
@davedoesdev: hello, same issue when running `npm install fido2-lib`:
```
$ npm install fido2-lib
 
> node-webcrypto-ossl@1.0.37 install /home/xavier/dev/tmp/fido2-server-demo/node_modules/fido2-lib/node_modules/node-webcrypto-ossl
> node-gyp rebuild

make : on entre dans le répertoire « /home/xavier/dev/tmp/fido2-server-demo/node_modules/fido2-lib/node_modules/node-webcrypto-ossl/build »
  CXX(target) Release/obj.target/nodessl/src/main.o
  CXX(target) Release/obj.target/nodessl/src/core/key_exp.o
  CXX(target) Release/obj.target/nodessl/src/core/scoped_ssl.o
  CXX(target) Release/obj.target/nodessl/src/core/logger.o
  CXX(target) Release/obj.target/nodessl/src/core/excep.o
  CXX(target) Release/obj.target/nodessl/src/core/digest.o
  CXX(target) Release/obj.target/nodessl/src/core/bn.o
../src/core/bn.cpp: In function ‘long unsigned int read_word_padded(const BIGNUM*, size_t)’:
../src/core/bn.cpp:36:17: error: invalid use of incomplete type ‘const BIGNUM {aka const struct bignum_st}’
  BN_ULONG l = in->d[constant_time_select_ulong(
                 ^~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ../src/core/bn.h:5,
                 from ../src/core/bn.cpp:1:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
...
```

**Comment by apowers313** [comment]
@guimard Did you update your node.js version, per [rmhrisk's comment](https://github.com/apowers313/fido2-server-demo/issues/5#issuecomment-397331516)?

**Comment by davedoesdev** [comment]
I'm wondering if your version of Node was configured with `/configure --openssl-use-sys`

**Comment by guimard** [comment]
Hello, I'm using packaged Node.js, built using:
```
--without-npm \
--without-snapshot \
--shared-openssl \
--shared-zlib \
--shared-cares \
--shared-nghttp2 \
--shared-http-parser \
--with-intl=system-icu \
--prefix=/usr \
--openssl-use-def-ca-store \
--shared-libuv
```

**Comment by apowers313** [comment]
@guimard Did you update your node.js version, per [rmhrisk's comment](https://github.com/apowers313/fido2-server-demo/issues/5#issuecomment-397331516)?

**Comment by guimard** [comment]
I can't update Node.js without using an official Debian package. Waiting for 10.0...

**Comment by apowers313** [comment]
Well, switching to a non-compiled version of a WebCrypto polyfill didn't work out: PeculiarVentures/PKI.js#178 ...

@guimard If I built you a Docker container, would you use that instead? I'm open to other ideas too...

**Comment by silverstar235** [comment]
Hello, why I can not run fido2-server-demo, in command line, i met this issue: "process.getuid is not a function..." error from component-director.js. In addition, debugging code with index.js has been lost the lib/main.js. I am using Node 8 8.11.1 and npm version 5.6.0

**Comment by davedoesdev** [comment]
@guimard did you manage to try nvm?

**Comment by apowers313** [comment]
Also, there's a Docker image now if you want to try that route:
https://hub.docker.com/r/apowers313/fido2-server/

**Comment by guimard** [comment]
Thanks ! This is exactly what I need

**Comment by apowers313** [comment]
Happy to help. :)

Open up a new issue if you have any problems with it.
